version: "3.7"
services:
    wikitten:
        pid: wikitten-7.4
        container_name: wikitten-7.4
        image: wikitten-7.4
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ../:/var/www/html
            - ${LIBRARY_FOLDER}:/var/www/html/library
            - ./logs:/var/log/php/
        env_file:
            - .env
        restart: always
